# base dir for data upload conf eg, data_base_dir={FATE}
# also used for accessing local files when running standalone mode
# examples/data/breast_hetero_guest.csv -> $data_base_dir/examples/data/breast_hetero_guest.csv
data_base_dir: path(FATE)

# directory dedicated to fate_test job file storage, default cache location={FATE}/examples/cache/
cache_directory: examples/cache/
# directory stores performance benchmark suites, default location={FATE}/examples/benchmark_performance
performance_template_directory: examples/benchmark_performance/
# directory stores flow test config, default location={FATE}/examples/flow_test_template/hetero_lr/flow_test_config.yaml
flow_test_config_directory: examples/flow_test_template/hetero_lr/flow_test_config.yaml

# directory stores testsuite file with min_test data sets to upload,
# default location={FATE}/examples/data/upload_config/min_test_data_testsuite.yaml
min_test_data_config: examples/data/upload_config/min_test_data_testsuite.yaml
# directory stores testsuite file with all example data sets to upload,
# default location={FATE}/examples/data/upload_config/all_examples_data_testsuite.yaml
all_examples_data_config: examples/data/upload_config/all_examples_data_testsuite.yaml

# directory where FATE code locates, default installation location={FATE}/fate
# python/ml -> $fate_base/python/ml
fate_base: path(FATE)/

# whether to delete data in suites after all jobs done
clean_data: true


# participating parties' id and corresponding flow service ip & port information
parties:
  guest: [ '9999' ]
  host: [ '10000', '9999' ]
  arbiter: [ '10000' ]
services:
  - flow_services:
      - { address: 127.0.0.1:9380, parties: [ '9999', '10000' ] }
    serving_setting:
      address: 127.0.0.1:8059
